pool:
  vmImage: Ubuntu 16.04
steps:
  - task: InstallMATLAB@0
  - task: RunMATLABTests@0
    inputs:
      sourceFolder: main
  - task: RunMATLABCommand@0
    inputs:
      command: addpath('main'); results = runtests('IncludeSubfolders', true); assertSuccess(results);