version: 2.1
orbs:
  matlab: mathworks/matlab@0
  codecov: codecov/codecov@1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests:
          source-folder: main
      - matlab/run-command:
          command: addpath('main'); results = runtests('IncludeSubfolders', true); assertSuccess(results);